coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 80%

ignore:
  - "src/test/"
  - "webapp/test/"
  - "venv*/"
  - "htmlcov/"